### ISSUE TITLE
Error encountered while testing hierarchical topology in Chipyard 1.8.1

### ISSUE THREAD

**Issue by astrohan** [ucb-bar/constellation#40]
Hi, guys

I've encountered while testing hierarchical topology in Chipyard 1.8.1. I tried to run TestConfig66, 67, and 68, but encountered a FIRRTL error while running 67 and 68.(66 seems not have an error)

I am using the Chipyard 1.8.1 tag and suspect that there may be an issue with TestConfig67 and 68. If there is a fixed version of these tests available, could you please share it with me?

Thank you in advance.

**Comment by jerryz123** [comment]
Can you upload the firrtl error here?

**Comment by astrohan** [comment]
Wow, thanks for the quick response.   
Here it is. (I sincerely admire your work^^)
```
[info] running chipyard.Generator --target-dir /home/astrohan/git/riscv/chipyard/sims/verilator/generated-src/constellation.test.TestHarness.TestConfig67 --name constellation.test.TestHarness.TestConfig67 --top-module constellation.test.TestHarness --legacy-configs constellation.test:TestConfig67
Constellation: test Checking full connectivity
Constellation: test Checking virtual subnet connectivity
Constellation: test Checking for possibility of deadlock
Constellation: test Finished parameter validation
[error] (run-main-0) java.lang.reflect.InvocationTargetException
[error] java.lang.reflect.InvocationTargetException
[error]         at ... ()
[error]         at freechips.rocketchip.stage.phases.PreElaboration.$anonfun$transform$1(PreElaboration.scala:36)
[error]         at ... ()
[error]         at ... (Stack trace trimmed to user code only. Rerun with --full-stacktrace to see the full stack trace)
[error] Caused by: java.lang.IllegalArgumentException: requirement failed: All output BitPats and default BitPat must have the same length
[error]         at scala.Predef$.require(Predef.scala:281)
[error]         at chisel3.util.experimental.decode.QMCMinimizer$.minimize(QMCMinimizer.scala:226)
[error]         at chisel3.util.experimental.decode.decoder$.$anonfun$apply$1(decoder.scala:24)
[error]         at scala.collection.immutable.Map$EmptyMap$.getOrElse(Map.scala:104)
[error]         at chisel3.util.experimental.decode.decoder$.apply(decoder.scala:24)
[error]         at freechips.rocketchip.rocket.DecodeLogic$.apply(Decode.scala:25)
[error]         at constellation.router.Prioritizing.$anonfun$prioritizing$14(Prioritizing.scala:60)
[error]         at constellation.router.Prioritizing.$anonfun$prioritizing$14$adapted(Prioritizing.scala:52)
[error]         at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
[error]         at scala.collection.immutable.Range.foreach(Range.scala:158)
[error]         at scala.collection.TraversableLike.map(TraversableLike.scala:238)
[error]         at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
[error]         at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error]         at constellation.router.Prioritizing.$anonfun$prioritizing$13(Prioritizing.scala:52)
[error]         at constellation.router.Prioritizing.$anonfun$prioritizing$13$adapted(Prioritizing.scala:52)
[error]         at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
[error]         at scala.collection.immutable.Range.foreach(Range.scala:158)
[error]         at scala.collection.TraversableLike.map(TraversableLike.scala:238)
[error]         at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
[error]         at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error]         at constellation.router.Prioritizing.$anonfun$prioritizing$12(Prioritizing.scala:52)
[error]         at chisel3.internal.prefix$.apply(prefix.scala:48)
[error]         at constellation.router.Prioritizing.$anonfun$prioritizing$11(Prioritizing.scala:52)
[error]         at chisel3.internal.plugin.package$.autoNameRecursively(package.scala:33)
[error]         at constellation.router.Prioritizing.prioritizing(Prioritizing.scala:52)
[error]         at constellation.router.Prioritizing.prioritizing$(Prioritizing.scala:15)
[error]         at constellation.router.PrioritizingSingleVCAllocator.prioritizing(Prioritizing.scala:107)
[error]         at constellation.router.Prioritizing.inputAllocPolicy(Prioritizing.scala:98)
[error]         at constellation.router.Prioritizing.inputAllocPolicy$(Prioritizing.scala:91)
[error]         at constellation.router.PrioritizingSingleVCAllocator.inputAllocPolicy(Prioritizing.scala:107)
[error]         at constellation.router.SingleVCAllocator.<init>(SingleVCAllocator.scala:42)
[error]         at constellation.router.PrioritizingSingleVCAllocator.<init>(Prioritizing.scala:107)
[error]         at constellation.test.TestConfig67$$anonfun$294.$anonfun$new$22(Configs.scala:706)
[error]         at constellation.router.Router$$anon$1.$anonfun$vc_allocator$2(Router.scala:133)
[error]         at chisel3.Module$.do_apply(Module.scala:53)
[error]         at constellation.router.Router$$anon$1.$anonfun$vc_allocator$1(Router.scala:131)
[error]         at chisel3.internal.plugin.package$.autoNameRecursively(package.scala:33)
[error]         at constellation.router.Router$$anon$1.<init>(Router.scala:131)
[error]         at constellation.router.Router.$anonfun$module$1(Router.scala:89)
[error]         at chisel3.internal.plugin.package$.autoNameRecursively(package.scala:33)
[error]         at constellation.router.Router.module$lzycompute(Router.scala:89)
[error]         at constellation.router.Router.module(Router.scala:89)
[error]         at constellation.router.Router.module(Router.scala:67)
[error]         at freechips.rocketchip.diplomacy.LazyModuleImpLike.$anonfun$instantiate$3(LazyModule.scala:278)
[error]         at chisel3.Module$.do_apply(Module.scala:53)
[error]         at freechips.rocketchip.diplomacy.LazyModuleImpLike.$anonfun$instantiate$2(LazyModule.scala:278)
[error]         at chisel3.internal.plugin.package$.autoNameRecursively(package.scala:33)
[error]         at freechips.rocketchip.diplomacy.LazyModuleImpLike.$anonfun$instantiate$1(LazyModule.scala:278)
[error]         at scala.collection.immutable.List.flatMap(List.scala:338)
[error]         at freechips.rocketchip.diplomacy.LazyModuleImpLike.instantiate(LazyModule.scala:276)
[error]         at freechips.rocketchip.diplomacy.LazyModuleImpLike.instantiate$(LazyModule.scala:273)
[error]         at freechips.rocketchip.diplomacy.LazyRawModuleImp.instantiate(LazyModule.scala:344)
[error]         at freechips.rocketchip.diplomacy.LazyRawModuleImp.$anonfun$x$22$2(LazyModule.scala:357)
[error]         at chisel3.withClockAndReset$.apply(MultiClock.scala:26)
[error]         at freechips.rocketchip.diplomacy.LazyRawModuleImp.$anonfun$x$22$1(LazyModule.scala:357)
[error]         at chisel3.internal.plugin.package$.autoNameRecursivelyProduct(package.scala:48)
[error]         at freechips.rocketchip.diplomacy.LazyRawModuleImp.<init>(LazyModule.scala:356)
[error]         at freechips.rocketchip.prci.Domain$$anon$1.<init>(ClockDomain.scala:10)
[error]         at freechips.rocketchip.prci.Domain.$anonfun$module$1(ClockDomain.scala:10)
[error]         at chisel3.internal.plugin.package$.autoNameRecursively(package.scala:33)
[error]         at freechips.rocketchip.prci.Domain.module$lzycompute(ClockDomain.scala:10)
[error]         at freechips.rocketchip.prci.Domain.module(ClockDomain.scala:10)
[error]         at freechips.rocketchip.prci.Domain.module(ClockDomain.scala:7)
[error]         at freechips.rocketchip.diplomacy.LazyModuleImpLike.$anonfun$instantiate$3(LazyModule.scala:278)
[error]         at chisel3.Module$.do_apply(Module.scala:53)
[error]         at freechips.rocketchip.diplomacy.LazyModuleImpLike.$anonfun$instantiate$2(LazyModule.scala:278)
[error]         at chisel3.internal.plugin.package$.autoNameRecursively(package.scala:33)
[error]         at freechips.rocketchip.diplomacy.LazyModuleImpLike.$anonfun$instantiate$1(LazyModule.scala:278)
[error]         at scala.collection.immutable.List.flatMap(List.scala:338)
[error]         at freechips.rocketchip.diplomacy.LazyModuleImpLike.instantiate(LazyModule.scala:276)
[error]         at freechips.rocketchip.diplomacy.LazyModuleImpLike.instantiate$(LazyModule.scala:273)
[error]         at freechips.rocketchip.diplomacy.LazyModuleImp.instantiate(LazyModule.scala:335)
[error]         at freechips.rocketchip.diplomacy.LazyModuleImp.$anonfun$x$21$1(LazyModule.scala:337)
[error]         at chisel3.internal.plugin.package$.autoNameRecursivelyProduct(package.scala:48)
[error]         at freechips.rocketchip.diplomacy.LazyModuleImp.<init>(LazyModule.scala:337)
[error]         at constellation.noc.NoC$$anon$1.<init>(NoC.scala:137)
[error]         at constellation.noc.NoC.$anonfun$module$1(NoC.scala:137)
[error]         at chisel3.internal.plugin.package$.autoNameRecursively(package.scala:33)
[error]         at constellation.noc.NoC.module$lzycompute(NoC.scala:137)
[error]         at constellation.noc.NoC.module(NoC.scala:137)
[error]         at constellation.test.TestHarness.$anonfun$noc$2(TestHarness.scala:237)
[error]         at chisel3.Module$.do_apply(Module.scala:53)
[error]         at constellation.test.TestHarness.$anonfun$noc$1(TestHarness.scala:237)
[error]         at chisel3.internal.plugin.package$.autoNameRecursively(package.scala:33)
[error]         at constellation.test.TestHarness.<init>(TestHarness.scala:237)
[error]         at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[error]         at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[error]         at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[error]         at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[error]         at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[error]         at freechips.rocketchip.stage.phases.PreElaboration.$anonfun$transform$1(PreElaboration.scala:36)
[error]         at chisel3.Module$.do_apply(Module.scala:53)
[error]         at chisel3.stage.phases.Elaborate.$anonfun$transform$2(Elaborate.scala:33)
[error]         at chisel3.internal.Builder$.$anonfun$build$1(Builder.scala:720)
[error]         at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
[error]         at chisel3.internal.Builder$.build(Builder.scala:715)
[error]         at chisel3.stage.phases.Elaborate.$anonfun$transform$1(Elaborate.scala:33)
[error]         at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:245)
[error]         at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[error]         at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[error]         at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[error]         at scala.collection.TraversableLike.flatMap(TraversableLike.scala:245)
[error]         at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:242)
[error]         at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
[error]         at chisel3.stage.phases.Elaborate.transform(Elaborate.scala:28)
[error]         at chisel3.stage.phases.Elaborate.transform(Elaborate.scala:21)
[error]         at firrtl.options.phases.DeletedWrapper.internalTransform(DeletedWrapper.scala:38)
[error]         at firrtl.options.phases.DeletedWrapper.internalTransform(DeletedWrapper.scala:15)
[error]         at firrtl.options.Translator.transform(Phase.scala:248)
[error]         at firrtl.options.Translator.transform$(Phase.scala:248)
[error]         at firrtl.options.phases.DeletedWrapper.transform(DeletedWrapper.scala:15)
[error]         at firrtl.options.DependencyManager.$anonfun$transform$5(DependencyManager.scala:280)
[error]         at firrtl.Utils$.time(Utils.scala:181)
[error]         at firrtl.options.DependencyManager.$anonfun$transform$3(DependencyManager.scala:280)
[error]         at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
[error]         at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
[error]         at scala.collection.immutable.List.foldLeft(List.scala:89)
[error]         at firrtl.options.DependencyManager.transform(DependencyManager.scala:269)
[error]         at firrtl.options.DependencyManager.transform$(DependencyManager.scala:255)
[error]         at firrtl.options.PhaseManager.transform(DependencyManager.scala:443)
[error]         at chisel3.stage.ChiselStage.run(ChiselStage.scala:45)
[error]         at firrtl.options.Stage$$anon$1.transform(Stage.scala:43)
[error]         at firrtl.options.Stage$$anon$1.transform(Stage.scala:43)
[error]         at firrtl.options.phases.DeletedWrapper.internalTransform(DeletedWrapper.scala:38)
[error]         at firrtl.options.phases.DeletedWrapper.internalTransform(DeletedWrapper.scala:15)
[error]         at firrtl.options.Translator.transform(Phase.scala:248)
[error]         at firrtl.options.Translator.transform$(Phase.scala:248)
[error]         at firrtl.options.phases.DeletedWrapper.transform(DeletedWrapper.scala:15)
[error]         at firrtl.options.Stage.$anonfun$transform$5(Stage.scala:47)
[error]         at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
[error]         at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
[error]         at scala.collection.immutable.List.foldLeft(List.scala:89)
[error]         at firrtl.options.Stage.$anonfun$transform$3(Stage.scala:47)
[error]         at logger.Logger$.$anonfun$makeScope$2(Logger.scala:137)
[error]         at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
[error]         at logger.Logger$.makeScope(Logger.scala:135)
[error]         at firrtl.options.Stage.transform(Stage.scala:47)
[error]         at firrtl.options.Stage.transform(Stage.scala:17)
[error]         at firrtl.options.phases.DeletedWrapper.internalTransform(DeletedWrapper.scala:38)
[error]         at firrtl.options.phases.DeletedWrapper.internalTransform(DeletedWrapper.scala:15)
[error]         at firrtl.options.Translator.transform(Phase.scala:248)
[error]         at firrtl.options.Translator.transform$(Phase.scala:248)
[error]         at firrtl.options.phases.DeletedWrapper.transform(DeletedWrapper.scala:15)
[error]         at firrtl.options.DependencyManager.$anonfun$transform$5(DependencyManager.scala:280)
[error]         at firrtl.Utils$.time(Utils.scala:181)
[error]         at firrtl.options.DependencyManager.$anonfun$transform$3(DependencyManager.scala:280)
[error]         at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
[error]         at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
[error]         at scala.collection.immutable.List.foldLeft(List.scala:89)
[error]         at firrtl.options.DependencyManager.transform(DependencyManager.scala:269)
[error]         at firrtl.options.DependencyManager.transform$(DependencyManager.scala:255)
[error]         at firrtl.options.PhaseManager.transform(DependencyManager.scala:443)
[error]         at chisel3.stage.ChiselStage.run(ChiselStage.scala:45)
[error]         at firrtl.options.Stage$$anon$1.transform(Stage.scala:43)
[error]         at firrtl.options.Stage$$anon$1.transform(Stage.scala:43)
[error]         at firrtl.options.phases.DeletedWrapper.internalTransform(DeletedWrapper.scala:38)
[error]         at firrtl.options.phases.DeletedWrapper.internalTransform(DeletedWrapper.scala:15)
[error]         at firrtl.options.Translator.transform(Phase.scala:248)
[error]         at firrtl.options.Translator.transform$(Phase.scala:248)
[error]         at firrtl.options.phases.DeletedWrapper.transform(DeletedWrapper.scala:15)
[error]         at firrtl.options.Stage.$anonfun$transform$5(Stage.scala:47)
[error]         at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
[error]         at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
[error]         at scala.collection.immutable.List.foldLeft(List.scala:89)
[error]         at firrtl.options.Stage.$anonfun$transform$3(Stage.scala:47)
[error]         at logger.Logger$.$anonfun$makeScope$2(Logger.scala:137)
[error]         at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
[error]         at logger.Logger$.makeScope(Logger.scala:135)
[error]         at firrtl.options.Stage.transform(Stage.scala:47)
[error]         at firrtl.options.Stage.execute(Stage.scala:58)
[error]         at firrtl.options.StageMain.main(Stage.scala:71)
[error]         at chipyard.Generator.main(Generator.scala)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[error]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[error] stack trace is suppressed; run last Compile / bgRunMain for the full output
[error] Nonzero exit code: 1
[error] (Compile / runMain) Nonzero exit code: 1
[error] Total time: 16 s, completed Mar 25, 2023, 5:22:13 PM
```

**Comment by jerryz123** [comment]
What commit of constellation are you using?

**Comment by astrohan** [comment]
This is what I used commit for constellation
```
commit b93fde3e2824f728c404e08984046d41679ec31f (HEAD)
Author: Jerry Zhao <jerryz123@berkeley.edu>
Date:   Tue Sep 27 22:07:28 2022 -0700

    Support shared pbus
```

And this is the commit for corresponding chipyard
```
commit 004297b6a8c01be1b2110c4cf4f9393ae1ff8805 (HEAD, tag: 1.8.1, origin/stable)
Merge: 3bc56ac8 bdeb496e
Author: Sagar Karandikar <sagark@eecs.berkeley.edu>
Date:   Tue Oct 18 19:07:06 2022 -0700

    Merge pull request #1260 from ucb-bar/run-ci

    Test conda lock for RTD
```

**Comment by jerryz123** [comment]
Can you try switching to Chipyard 1.9.0 (recently released)? I feel like this may have been fixed.

Thanks so much for trying to test this project out. I really appreciate it.

**Comment by astrohan** [comment]
I attempted to build chipyard 1.9.0, but encountered build errors(Unresolved dependencies) which resulted in failure.  
I require some time to determine whether the errors are a result of issues in my environment.  
(Are there any known issues with the 1.9.0 build?)

**Comment by astrohan** [comment]
Hi, 

I have checked 66, 67, and 68.
66 and 67 are confirmed to be working in version 1.9.0.
However, there is still an error with 68.

```
[error] java.lang.IllegalArgumentException: advance1(1073741824, 2147483616): a1=[Ljava.lang.Object;@3a431f52, a2=[[Ljava.lang.Object;@1c231b04, a3=[[[Ljava.lang.Object;@1fb86da6, a4=[[[[Ljava.lang.Object;@2d984e64, a5=[[[[[Ljava.lang.Object;@f836d0a, a6=[[[[[[Ljava.lang.Object;@b7cacc5, depth=6
[error]         at scala.collection.immutable.VectorBuilder.advance1(Vector.scala:1657)
[error]         at scala.collection.immutable.VectorBuilder.advance(Vector.scala:1612)
[error]         at scala.collection.immutable.VectorBuilder.addArr1(Vector.scala:1578)
[error]         at scala.collection.immutable.VectorBuilder.addVector(Vector.scala:1591)
[error]         at scala.collection.immutable.VectorBuilder.addAll(Vector.scala:1602)
[error]         at scala.collection.immutable.VectorBuilder.addAll(Vector.scala:1388)
[error]         at scala.collection.StrictOptimizedIterableOps.flatMap(StrictOptimizedIterableOps.scala:118)
[error]         at scala.collection.StrictOptimizedIterableOps.flatMap$(StrictOptimizedIterableOps.scala:105)
[error]         at scala.collection.immutable.Vector.flatMap(Vector.scala:113)
[error]         at chisel3.util.experimental.decode.QMCMinimizer$.$anonfun$getCover$7(QMCMinimizer.scala:212)
[error]         at scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:183)
[error]         at scala.collection.LinearSeqOps.foldLeft$(LinearSeq.scala:179)
[error]         at scala.collection.immutable.List.foldLeft(List.scala:79)
[error]         at chisel3.util.experimental.decode.QMCMinimizer$.getCover(QMCMinimizer.scala:212)
[error]         at chisel3.util.experimental.decode.QMCMinimizer$.$anonfun$minimize$12(QMCMinimizer.scala:302)
[error]         at chisel3.util.experimental.decode.QMCMinimizer$.$anonfun$minimize$12$adapted(QMCMinimizer.scala:244)
[error]         at scala.collection.StrictOptimizedIterableOps.flatMap(StrictOptimizedIterableOps.scala:118)
[error]         at scala.collection.StrictOptimizedIterableOps.flatMap$(StrictOptimizedIterableOps.scala:105)
[error]         at scala.collection.immutable.Range.flatMap(Range.scala:59)
[error]         at chisel3.util.experimental.decode.QMCMinimizer$.minimize(QMCMinimizer.scala:244)
[error]         at chisel3.util.experimental.decode.decoder$.$anonfun$apply$1(decoder.scala:25)
[error]         at scala.collection.immutable.Map$EmptyMap$.getOrElse(Map.scala:226)
[error]         at chisel3.util.experimental.decode.decoder$.apply(decoder.scala:25)
[error]         at freechips.rocketchip.rocket.DecodeLogic$.apply(Decode.scala:25)
[error]         at constellation.router.Prioritizing.$anonfun$prioritizing$19(Prioritizing.scala:68)
[error]         at constellation.router.Prioritizing.$anonfun$prioritizing$19$adapted(Prioritizing.scala:63)
[error]         at scala.collection.immutable.Range.map(Range.scala:59)
[error]         at constellation.router.Prioritizing.$anonfun$prioritizing$18(Prioritizing.scala:63)
[error]         at constellation.router.Prioritizing.$anonfun$prioritizing$18$adapted(Prioritizing.scala:63)
[error]         at scala.collection.immutable.Range.map(Range.scala:59)
[error]         at constellation.router.Prioritizing.$anonfun$prioritizing$17(Prioritizing.scala:63)
[error]         at chisel3.internal.prefix$.apply(prefix.scala:48)
[error]         at constellation.router.Prioritizing.$anonfun$prioritizing$16(Prioritizing.scala:63)
[error]         at chisel3.internal.plugin.package$.autoNameRecursively(package.scala:33)
[error]         at constellation.router.Prioritizing.prioritizing(Prioritizing.scala:63)
[error]         at constellation.router.Prioritizing.prioritizing$(Prioritizing.scala:15)
[error]         at constellation.router.PrioritizingSingleVCAllocator.prioritizing(Prioritizing.scala:115)
[error]         at constellation.router.Prioritizing.inputAllocPolicy(Prioritizing.scala:106)
[error]         at constellation.router.Prioritizing.inputAllocPolicy$(Prioritizing.scala:99)
[error]         at constellation.router.PrioritizingSingleVCAllocator.inputAllocPolicy(Prioritizing.scala:115)
[error]         at constellation.router.SingleVCAllocator.$anonfun$new$13(SingleVCAllocator.scala:42)
[error]         at chisel3.Data.$anonfun$$colon$eq$1(Data.scala:791)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[error]         at chisel3.internal.prefix$.apply(prefix.scala:31)
[error]         at chisel3.Data.$colon$eq(Data.scala:791)
[error]         at constellation.router.SingleVCAllocator.<init>(SingleVCAllocator.scala:41)
[error]         at constellation.router.PrioritizingSingleVCAllocator.<init>(Prioritizing.scala:115)
[error]         at constellation.test.TestConfig68$$anonfun$295.$anonfun$new$28(Configs.scala:740)
[error]         at constellation.router.Router$$anon$1.$anonfun$vc_allocator$2(Router.scala:133)
[error]         at chisel3.Module$.do_apply(Module.scala:53)
[error]         at constellation.router.Router$$anon$1.$anonfun$vc_allocator$1(Router.scala:131)
[error]         at chisel3.internal.plugin.package$.autoNameRecursively(package.scala:33)
[error]         at constellation.router.Router$$anon$1.<init>(Router.scala:131)
[error]         at constellation.router.Router.$anonfun$module$1(Router.scala:89)
[error]         at chisel3.internal.plugin.package$.autoNameRecursively(package.scala:33)
[error]         at constellation.router.Router.module$lzycompute(Router.scala:89)
[error]         at constellation.router.Router.module(Router.scala:89)
[error]         at constellation.router.Router.module(Router.scala:67)
[error]         at freechips.rocketchip.diplomacy.LazyModuleImpLike.$anonfun$instantiate$15(LazyModule.scala:334)
[error]         at chisel3.Module$.do_apply(Module.scala:53)
[error]         at freechips.rocketchip.diplomacy.LazyModuleImpLike.$anonfun$instantiate$14(LazyModule.scala:334)
[error]         at chisel3.internal.plugin.package$.autoNameRecursively(package.scala:33)
[error]         at freechips.rocketchip.diplomacy.LazyModuleImpLike.$anonfun$instantiate$13(LazyModule.scala:334)
[error]         at scala.Option.getOrElse(Option.scala:201)
[error]         at freechips.rocketchip.diplomacy.LazyModuleImpLike.$anonfun$instantiate$1(LazyModule.scala:332)
[error]         at scala.collection.immutable.List.flatMap(List.scala:293)
[error]         at freechips.rocketchip.diplomacy.LazyModuleImpLike.instantiate(LazyModule.scala:308)
[error]         at freechips.rocketchip.diplomacy.LazyModuleImpLike.instantiate$(LazyModule.scala:305)
[error]         at freechips.rocketchip.diplomacy.LazyRawModuleImp.instantiate(LazyModule.scala:401)
[error]         at freechips.rocketchip.diplomacy.LazyRawModuleImp.$anonfun$x$23$2(LazyModule.scala:414)
[error]         at chisel3.withClockAndReset$.apply(MultiClock.scala:26)
[error]         at freechips.rocketchip.diplomacy.LazyRawModuleImp.$anonfun$x$23$1(LazyModule.scala:414)
[error]         at chisel3.internal.plugin.package$.autoNameRecursivelyProduct(package.scala:48)
[error]         at freechips.rocketchip.diplomacy.LazyRawModuleImp.<init>(LazyModule.scala:413)
[error]         at freechips.rocketchip.prci.Domain$Impl.<init>(ClockDomain.scala:11)
[error]         at freechips.rocketchip.prci.Domain.$anonfun$module$1(ClockDomain.scala:10)
[error]         at chisel3.internal.plugin.package$.autoNameRecursively(package.scala:33)
[error]         at freechips.rocketchip.prci.Domain.module$lzycompute(ClockDomain.scala:10)
[error]         at freechips.rocketchip.prci.Domain.module(ClockDomain.scala:10)
[error]         at freechips.rocketchip.prci.Domain.module(ClockDomain.scala:7)
[error]         at freechips.rocketchip.diplomacy.LazyModuleImpLike.$anonfun$instantiate$15(LazyModule.scala:334)
[error]         at chisel3.Module$.do_apply(Module.scala:53)
[error]         at freechips.rocketchip.diplomacy.LazyModuleImpLike.$anonfun$instantiate$14(LazyModule.scala:334)
[error]         at chisel3.internal.plugin.package$.autoNameRecursively(package.scala:33)
[error]         at freechips.rocketchip.diplomacy.LazyModuleImpLike.$anonfun$instantiate$13(LazyModule.scala:334)
[error]         at scala.Option.getOrElse(Option.scala:201)
[error]         at freechips.rocketchip.diplomacy.LazyModuleImpLike.$anonfun$instantiate$1(LazyModule.scala:332)
[error]         at scala.collection.immutable.List.flatMap(List.scala:293)
[error]         at freechips.rocketchip.diplomacy.LazyModuleImpLike.instantiate(LazyModule.scala:308)
[error]         at freechips.rocketchip.diplomacy.LazyModuleImpLike.instantiate$(LazyModule.scala:305)
[error]         at freechips.rocketchip.diplomacy.LazyModuleImp.instantiate(LazyModule.scala:392)
[error]         at freechips.rocketchip.diplomacy.LazyModuleImp.$anonfun$x$22$1(LazyModule.scala:394)
[error]         at chisel3.internal.plugin.package$.autoNameRecursivelyProduct(package.scala:48)
[error]         at freechips.rocketchip.diplomacy.LazyModuleImp.<init>(LazyModule.scala:394)
[error]         at constellation.noc.NoC$Impl.<init>(NoC.scala:138)
[error]         at constellation.noc.NoC.$anonfun$module$1(NoC.scala:137)
[error]         at chisel3.internal.plugin.package$.autoNameRecursively(package.scala:33)
[error]         at constellation.noc.NoC.module$lzycompute(NoC.scala:137)
[error]         at constellation.noc.NoC.module(NoC.scala:137)
[error]         at constellation.test.TestHarness.$anonfun$noc$2(TestHarness.scala:238)
[error]         at chisel3.Module$.do_apply(Module.scala:53)
[error]         at constellation.test.TestHarness.$anonfun$noc$1(TestHarness.scala:238)
[error]         at chisel3.internal.plugin.package$.autoNameRecursively(package.scala:33)
[error]         at constellation.test.TestHarness.<init>(TestHarness.scala:238)
[error]         at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[error]         at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[error]         at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[error]         at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[error]         at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[error]         at freechips.rocketchip.stage.phases.PreElaboration.$anonfun$transform$1(PreElaboration.scala:36)
[error]         at chisel3.Module$.do_apply(Module.scala:53)
[error]         at chisel3.stage.phases.Elaborate.$anonfun$transform$2(Elaborate.scala:40)
[error]         at chisel3.internal.Builder$.$anonfun$build$1(Builder.scala:807)
[error]         at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
[error]         at chisel3.internal.Builder$.build(Builder.scala:802)
[error]         at chisel3.stage.phases.Elaborate.$anonfun$transform$1(Elaborate.scala:40)
[error]         at scala.collection.immutable.List.flatMap(List.scala:293)
[error]         at scala.collection.immutable.List.flatMap(List.scala:79)
[error]         at chisel3.stage.phases.Elaborate.transform(Elaborate.scala:28)
[error]         at chisel3.stage.phases.Elaborate.transform(Elaborate.scala:21)
[error]         at firrtl.options.phases.DeletedWrapper.internalTransform(DeletedWrapper.scala:38)
[error]         at firrtl.options.phases.DeletedWrapper.internalTransform(DeletedWrapper.scala:15)
[error]         at firrtl.options.Translator.transform(Phase.scala:248)
[error]         at firrtl.options.Translator.transform$(Phase.scala:248)
[error]         at firrtl.options.phases.DeletedWrapper.transform(DeletedWrapper.scala:15)
[error]         at firrtl.options.DependencyManager.$anonfun$transform$5(DependencyManager.scala:280)
[error]         at firrtl.Utils$.time(Utils.scala:181)
[error]         at firrtl.options.DependencyManager.$anonfun$transform$3(DependencyManager.scala:280)
[error]         at scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:183)
[error]         at scala.collection.LinearSeqOps.foldLeft$(LinearSeq.scala:179)
[error]         at scala.collection.immutable.List.foldLeft(List.scala:79)
[error]         at firrtl.options.DependencyManager.transform(DependencyManager.scala:269)
[error]         at firrtl.options.DependencyManager.transform$(DependencyManager.scala:255)
[error]         at firrtl.options.PhaseManager.transform(DependencyManager.scala:443)
[error]         at chisel3.stage.ChiselStage.run(ChiselStage.scala:45)
[error]         at firrtl.options.Stage$$anon$1.transform(Stage.scala:43)
[error]         at firrtl.options.Stage$$anon$1.transform(Stage.scala:43)
[error]         at firrtl.options.phases.DeletedWrapper.internalTransform(DeletedWrapper.scala:38)
[error]         at firrtl.options.phases.DeletedWrapper.internalTransform(DeletedWrapper.scala:15)
[error]         at firrtl.options.Translator.transform(Phase.scala:248)
[error]         at firrtl.options.Translator.transform$(Phase.scala:248)
[error]         at firrtl.options.phases.DeletedWrapper.transform(DeletedWrapper.scala:15)
[error]         at firrtl.options.Stage.$anonfun$transform$5(Stage.scala:47)
[error]         at scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:183)
[error]         at scala.collection.LinearSeqOps.foldLeft$(LinearSeq.scala:179)
[error]         at scala.collection.immutable.List.foldLeft(List.scala:79)
[error]         at firrtl.options.Stage.$anonfun$transform$3(Stage.scala:47)
[error]         at logger.Logger$.$anonfun$makeScope$2(Logger.scala:137)
[error]         at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
[error]         at logger.Logger$.makeScope(Logger.scala:135)
[error]         at firrtl.options.Stage.transform(Stage.scala:47)
[error]         at firrtl.options.Stage.transform(Stage.scala:17)
[error]         at firrtl.options.phases.DeletedWrapper.internalTransform(DeletedWrapper.scala:38)
[error]         at firrtl.options.phases.DeletedWrapper.internalTransform(DeletedWrapper.scala:15)
[error]         at firrtl.options.Translator.transform(Phase.scala:248)
[error]         at firrtl.options.Translator.transform$(Phase.scala:248)
[error]         at firrtl.options.phases.DeletedWrapper.transform(DeletedWrapper.scala:15)
[error]         at firrtl.options.DependencyManager.$anonfun$transform$5(DependencyManager.scala:280)
[error]         at firrtl.Utils$.time(Utils.scala:181)
[error]         at firrtl.options.DependencyManager.$anonfun$transform$3(DependencyManager.scala:280)
[error]         at scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:183)
[error]         at scala.collection.LinearSeqOps.foldLeft$(LinearSeq.scala:179)
[error]         at scala.collection.immutable.List.foldLeft(List.scala:79)
[error]         at firrtl.options.DependencyManager.transform(DependencyManager.scala:269)
[error]         at firrtl.options.DependencyManager.transform$(DependencyManager.scala:255)
[error]         at firrtl.options.PhaseManager.transform(DependencyManager.scala:443)
[error]         at chisel3.stage.ChiselStage.run(ChiselStage.scala:45)
[error]         at firrtl.options.Stage$$anon$1.transform(Stage.scala:43)
[error]         at firrtl.options.Stage$$anon$1.transform(Stage.scala:43)
[error]         at firrtl.options.phases.DeletedWrapper.internalTransform(DeletedWrapper.scala:38)
[error]         at firrtl.options.phases.DeletedWrapper.internalTransform(DeletedWrapper.scala:15)
[error]         at firrtl.options.Translator.transform(Phase.scala:248)
[error]         at firrtl.options.Translator.transform$(Phase.scala:248)
[error]         at firrtl.options.phases.DeletedWrapper.transform(DeletedWrapper.scala:15)
[error]         at firrtl.options.Stage.$anonfun$transform$5(Stage.scala:47)
[error]         at scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:183)
[error]         at scala.collection.LinearSeqOps.foldLeft$(LinearSeq.scala:179)
[error]         at scala.collection.immutable.List.foldLeft(List.scala:79)
[error]         at firrtl.options.Stage.$anonfun$transform$3(Stage.scala:47)
[error]         at logger.Logger$.$anonfun$makeScope$2(Logger.scala:137)
[error]         at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
[error]         at logger.Logger$.makeScope(Logger.scala:135)
[error]         at firrtl.options.Stage.transform(Stage.scala:47)
[error]         at firrtl.options.Stage.execute(Stage.scala:58)
[error]         at firrtl.options.StageMain.main(Stage.scala:71)
[error]         at chipyard.Generator.main(Generator.scala)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[error]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[error] stack trace is suppressed; run last Compile / runMain for the full output
[error] (Compile / runMain) java.lang.reflect.InvocationTargetException
[error] Total time: 47 s, completed Apr 2, 2023, 2:23:23 AM
make: *** [/home/astrohan/git/riscv/chipyard_1.9.0/common.mk:110: /home/astrohan/git/riscv/chipyard_1.9.0/sims/verilator/generated-src/constellation.test.TestHarness.TestConfig68/constellation.test.TestHarness.TestConfig68.fir] Error 1
```

**Comment by jerryz123** [comment]
Thanks for the report, I'll look into this.

**Comment by jerryz123** [comment]
Can you try patching this commit into your local constellation? https://github.com/ucb-bar/constellation/commit/6a12a215ba5dda1b5806c7519c86dd9cd165efef

**Comment by astrohan** [comment]
All hierarchical NoC tests have been completed successfully with your latest patch^^

**Comment by jerryz123** [comment]
Great! Thanks for following up so quickly
